# Generated by Django 4.2.16 on 2026-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='given_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='return_date',
            field=models.DateField(),
        ),
    ]
